server:
  port: 5000

spring:
  application:
    name: UdineTour

udine:
  vertex:
    gemini:
      url: ${VERTEX_GEMINI_URL}
      apiKey: ${VERTEX_GEMINI_API_KEY}
      name:
        param:
          apiKey: ${VERTEX_GEMINI_NAME_PARAM_API_KEY:key}
  google:
    places:
      url: ${GOOGLE_PLACES_URL:https://maps.googleapis.com/maps/api/place/nearbysearch/json}
      apiKey: ${GOOGLE_PLACES_API_KEY}
