server:
  port: 5000

spring:
  application:
    name: UdineTour

udine:
  vertex:
    gemini:
      url: ${VERTEX_GEMINI_URL}
      api-key: ${VERTEX_GEMINI_API_KEY}
      connections-attempt: ${VERTEX_GEMINI_CONNECTIONS_ATTEMPT:3}
      name:
        param:
          apiKey: ${VERTEX_GEMINI_NAME_PARAM_API_KEY:key}
  google:
    places:
      url: ${GOOGLE_PLACES_URL:https://maps.googleapis.com/maps/api/place}
      nearby-search-path: ${GOOGLE_PLACES_NEARBY_SEARCH_PATH:/nearbysearch/json}
      details-path: ${GOOGLE_PLACES_DETAILS_PATH:/details/json}
      apiKey: ${GOOGLE_PLACES_API_KEY}
      types:
        - tourist_attraction
        - park

  text-to-speech:
    base-uri: ${TEXT_TO_SPEECH_BASE_URI:https://texttospeech.googleapis.com}
    path: ${TEXT_TO_SPEECH_PATH:/v1beta1/text:synthesize}
    apiKey: ${TEXT_TO_SPEECH_API_KEY}

  speech-to-text:
    base-uri: ${SPEECH_TO_TEXT_BASE_URI:https://speech.googleapis.com}
    path: ${SPEECH_TO_TEXT_PATH:/v1/speech:recognize}
    apiKey: ${SPEECH_TO_TEXT_API_KEY}

  openai:
    url: ${OPEN_AI_URL:https://api.openai.com/v1/chat/completions}
    api-key: ${OPEN_AI_API_KEY}

  wikipedia:
    url: ${WIKIPEDIA_URL:https://pt.wikipedia.org/w/api.php}
    action: ${WIKIPEDIA_ACTION:query}
    format: ${WIKIPEDIA_FORMAT:json}
    prop: ${WIKIPEDIA_PROP:extracts}
    explaintext: ${WIKIPEDIA_EXPLAINTEXT:""}
